tbl = read.table("em_test.txt")
pdf("em_ss.pdf")
plot(log2(tbl[,3]), log2(tbl[,2]), xlab="log2 sequence length", ylab="log2 time (ms)", type="b", lwd=2)
lines(log2(tbl[,c(3,1)]), col="red", lwd=2, type="b")
legend("topleft", c("solution C (one call per position)", "solution B (one call per state)"), lty=1, lwd=2, col=c("black", "red"))
dev.off()
